[theme]
primaryColor = "#1e40af"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[logger]
level = "warning"
