[theme]
primaryColor = "#1C355E"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#101820"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[logger]
level = "warning"
